const CREATE_TODO = "CREATE_TODO";
const DELETE_TODO = "DELETE_TODO";
const SEARCH_TODO = "SEARCH_TODO";
const TOGGLE_UPDATE = "TOGGLE_UPDATE";
const TOGGLE_TODO = "TOGGLE_TODO";

export default { CREATE_TODO, DELETE_TODO, SEARCH_TODO, TOGGLE_UPDATE, TOGGLE_TODO };